Git_FarmatodoWeb/FarmatodoWeb/Controllers/ContactoController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace FarmatodoWeb.Controllers
{
    public class ContactoController : Controller
    {
        private readonly ILogger<ContactoController> _logger;
        public ContactoController(ILogger<ContactoController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index(){
            return View();
        }
    }
}

Git_FarmatodoWeb/FarmatodoWeb/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FarmatodoWeb.Models;
using FarmatodoWeb.Data;
using FarmatodoWeb.Utils;
using Microsoft.EntityFrameworkCore;
using FarmatodoWeb.Filters;

namespace FarmatodoWeb.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ILogger<ProductoController> _logger;
        private readonly ApplicationDbContext _context;
        private List<Producto> ListaProductos;
        private Paginador<Producto> _Paginador;
        private readonly int _RegistrosPorPagina = 10;
//        private int dni;
//        private PersonaBase _personaBase;

        public ProductoController(ILogger<ProductoController> logger, ApplicationDbContext context/*, PersonaBase personaBase*/)
        {
            _logger = logger;
            _context = context;
//            _personaBase = personaBase;
                        //var productos=_context.Productos.Include(p=>p.TipoProducto).Include(p=>p.Marca).ToList();
            ListaProductos = _context.Productos.Include(p=>p.Categoria).AsNoTracking().ToList();
        }

        public IActionResult Index()
        {
            var listProductos=_context.Productos.OrderBy(s=>s.Id).ToList();
            return View("List", listProductos);
        }

        public IActionResult Create()
        {
            ViewBag.Categorias=_context.Categorias.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Producto objProducto){
            ViewBag.Categorias=_context.Categorias.ToList();
            if(ModelState.IsValid){
                _context.Add(objProducto);
                _context.SaveChanges();
                //return View(objProducto);
                return View();
            }
                return View();
        }
        public IActionResult Edit(int? id){
            ViewBag.Categorias=_context.Categorias.ToList();
            if(id==null){
                return NotFound();
            }
            var Producto=_context.Productos.Find(id);

            Modelos Modelo_Modelos=new Modelos();
            Modelo_Modelos.Modelo_Producto=Producto;

            if(Modelo_Modelos==null){
                return NotFound();
                // return RedirectToAction("List", "Producto");
            }else{
                return View(Modelo_Modelos);
            }
//            return View(Producto);
//            return View(Modelo_Modelos);
        }

        [HttpPost]
        public IActionResult Edit(int id, Modelos Modelo_Modelos){
            ViewBag.Categorias=_context.Categorias.ToList();
            if(ModelState.IsValid){
                _context.Update(Modelo_Modelos.Modelo_Producto);
                _context.SaveChanges();
            }
            //return View(Producto);
            //return RedirectToAction("List");
            return View(Modelo_Modelos);
        }

        // public IActionResult List()
        // {
        //     var listProductos=_context.Productos.OrderBy(s=>s.Id).ToList();
        //     return View("List", listProductos);
        // }
        
        public IActionResult Delete(int? id){
            var Producto=_context.Productos.Find(id);
            _context.Productos.Remove(Producto);
            _context.SaveChanges();
            return RedirectToAction(nameof(List));
        }
        
//3.0        [ServiceFilter(typeof(VerifySession))]
        public IActionResult List(string buscarProductos, int pagina = 1)
        {
            int _TotalRegistros = 0;
            int _TotalPaginas = 0;
            // FILTRO DE BÚSQUEDA
            // using (_context)
            // {
            // Filtramos el resultado por el 'texto de búqueda'
            if (!string.IsNullOrEmpty(buscarProductos))
            {
                foreach (var item in buscarProductos.Split(new char[] { ' ' },
                         StringSplitOptions.RemoveEmptyEntries))
                {
                    ListaProductos = ListaProductos.Where(x => x.Descripcion.Contains(item) //||
                                                  //x.Precio.Contains(item) 
                                                  //||
                                                  //x.Categorias.Contains(item)
                                                  ).ToList()
                                                  ;
                }
            }
            // }
            // SISTEMA DE PAGINACIÓN
            // using (_context)
            // {
            _TotalRegistros = ListaProductos.Count();
            // Obtenemos la 'página de registros' 
            ListaProductos = ListaProductos.OrderBy(x => x.Id)
                                             .Skip((pagina - 1) * _RegistrosPorPagina)
                                             .Take(_RegistrosPorPagina).ToList();
            // Número total de páginas
            _TotalPaginas = (int)Math.Ceiling((double)_TotalRegistros / _RegistrosPorPagina);

            // Instanciamos la 'Clase de paginación' y asignamos los nuevos valores
            _Paginador = new Paginador<Producto>()
            {
                RegistrosPorPagina = _RegistrosPorPagina,
                TotalRegistros = _TotalRegistros,
                TotalPaginas = _TotalPaginas,
                PaginaActual = pagina,
                BusquedaActual = buscarProductos,
                Resultado = ListaProductos
            };
            // }
            ViewData["palabra"]=buscarProductos;
            
            Modelos Modelo_Modelos=new Modelos();
            Modelo_Modelos.Modelo_Paginador_Producto=_Paginador;
            Modelo_Modelos.Modelo_IEnumerable_Persona=_context.Personas.ToList();
            //if(modeloPersona!=null){
            //    modeloPersona=_context.persona;
//                Modelo_Modelos.Modelo_IEnumerable_Persona=PersonaBase;
            //}else{
            //    modeloPersona=new PersonaBase();
            //    Modelo_Modelos.Modelo_IEnumerable_Persona=modeloPersona;
            //}
            Console.WriteLine("El nombre de la persona es: "+PersonaBase.Nombre);
            //return View(_Paginador);
//            TempData["ButtonValue"]=PersonaBase.Id;
            return View(Modelo_Modelos);
        }

        //public IActionResult List(){
        //    return View(model);
        //}
        public IActionResult Producto()
        {
            return View();
        }

        private void met(){
            Persona modeloPersona=_context.persona;
            Console.WriteLine("El nombre de la persona2 es: "+modeloPersona.Nombre);
        }
    }
}

Git_FarmatodoWeb/FarmatodoWeb/Controllers/SomosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace FarmatodoWeb.Controllers
{
    public class SomosController : Controller
    {
        private readonly ILogger<SomosController> _logger;

        public SomosController(ILogger<SomosController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index(){
            return View();
        }
    }
}

Git_FarmatodoWeb/FarmatodoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FarmatodoWeb</title>
    @* Bootstrap [Cargar primero] *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* Bootstrap [Cargar segundo] *@
    <script type="module" src="~/js/javascripts.js"></script>
    @* ïcon App Web *@
    <link href="/imagenes/LogoF1.png" rel="icon" type="image/x-icon" />
    <link href="/imagenes/LogoF1.png" rel="shortcut icon" type="image/x-icon" />
    @* Fuente Roboto *@
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    @* íconos *@
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" rel="stylesheet">
    @* Dropdown *@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    @* íconos Login Logout *@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @* Estilos [Cargar último!] *@
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/estilos.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" id="navegacion">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" id="letra">FarmatodoWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon" id="navegacionBarra" data-toggle="tooltip" data-placement="left" title="Menú"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index" id="letra">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Producto" asp-action="Create" id="letra">Registrar Producto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Producto" asp-action="List" id="letra">Productos</a>
                        </li>
                        <partial name="_RolPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container body-content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    <div id="espacio"></div>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year=> @DateTime.Now.Date | @DateTime.Now.Day/@DateTime.Now.Month/@DateTime.Now.Year - FarmatodoWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    @* <footer class="footerx text-center" id="letra" style="margin-top: 10%!important; margin-bottom: -50%;"> *@
    <footer class="text-center" id="letra">
        <div style="overflow: auto">
            <div class="container p-4;">
                <section class="mb-4">
                    <a class="btn btn-outline-primary btn-floating m-1" href="https://google.com.pe" role="button" title="facebook"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-primary btn-floating m-1" href="https://google.com.pe" role="button" title="twitter"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-primary btn-floating m-1" href="https://google.com.pe" role="button" title="google"><i class="fab fa-google"></i></a>
                    <a class="btn btn-outline-primary btn-floating m-1" href="https://google.com.pe" role="button" title="instagram"><i class="fab fa-instagram"></i></a>
                    <a class="btn btn-outline-primary btn-floating m-1" href="https://google.com.pe" role="button" title="linkedin"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-outline-primary btn-floating m-1" href="https://google.com.pe" role="button" title="github"><i class="fab fa-github"></i></a>
                </section>

                <section class="">
                    <form action="">
                        <div class="row d-flex justify-content-center">
                        <div class="col-auto">
                            <p class="pt-2">
                            <strong>Suscribirse a nuestro boletín</strong>
                            </p>
                        </div>

                        <div class="col-md-5 col-12">
                            <div class="form-outline form-white mb-4">
                            <input type="email" id="form5Example2" class="form-control" />
                            <label class="form-label" for="form5Example2">Dirección de correo electrónico</label>
                            </div>
                        </div>

                        <div class="col-auto">
                            <button type="submit" class="btn btn-outline-primary mb-4">
                            Suscribirse
                            </button>
                        </div>
                        </div>
                    </form>
                </section>

                <section class="mb-4">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                </section>

                <section class="">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                            <h5 class="text-uppercase">Información</h5>
                            <ul class="list-unstyled mb-0" id="letra">
                                <li><a class="miLink" href="https://google.com.pe">Link 1</a></li>
                                <li><a class="miLink" href="https://google.com.pe">Link 2</a></li>
                            </ul>
                        </div>

                        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                            @* <h5 class="text-uppercase">Contáctanos</h5> *@
                            <a class="text-white" asp-area="" asp-controller="Contacto" asp-action="Index"> CONTÁCTANOS </a>
                            <ul class="list-unstyled mb-0" id="letra">
                                <li><a class="miLink" href="https://google.com.pe">Link 1</a></li>
                                <li><a class="miLink" href="https://google.com.pe">Link 2</a></li>
                            </ul>
                        </div>

                        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                            @* <h5 class="text-uppercase" asp-controller="Somos" asp-action="Index">Nosotros</h5> *@
                            <a class="text-uppercase text-white" asp-area="" asp-controller="Somos" asp-action="Index"> NOSOTROS </a>
                            <ul class="list-unstyled mb-0" id="letra">
                                <li><a class="miLink" href="https://google.com.pe">Link 1</a></li>
                                <li><a class="miLink" href="https://google.com.pe">Link 2</a></li>
                            </ul>
                        </div>

                        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                            <h5 class="text-uppercase">Ubicación</h5>
                            <ul class="list-unstyled mb-0" id="letra">
                                <li><a class="miLink" href="https://google.com.pe">Link 1</a></li>
                                <li><a class="miLink" href="https://google.com.pe">Link 2</a></li>
                            </ul>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </footer>
    @* <footer class="footer text-muted text-center">
        <div style="overflow: auto; background: #0EA900;">
            <div class="container" style="color: white;">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8" id="interlineadoFooter">Dirección: Av. La Fontana 1250. Urb. Santa Patricia. La Molina</div>
                    <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2" id="interlineadoFooter"><p>RESET S.A.C</p></div>
                    <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2" id="interlineadoFooter"><p>RESET S.A.C</p></div>
                </div>
            </div>
        </div>
        <div style="overflow: auto; background: black;">
            <div class="container" style="color: white;">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8" id="interlineadoFooter">&copy; 2021 RESET S.A.C. | Todos los derechos reservados</div>
                    <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2" id="interlineadoFooter"><p>RESET S.A.C</p></div>
                    <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2" id="interlineadoFooter"><p>RESET S.A.C</p></div>
                </div>
            </div>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    @* @RenderSection("Scripts2", required: false) *@
    <script>
        
    </script>
</body>
</html>

Git_FarmatodoWeb/FarmatodoWeb/Views/Shared/_LayoutAcceso.cshtml
@{
    Layout="_Layout";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3 col-xl-6 offset-xl-3">
            <div class="card login-logout-tab" id="panelAuto">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        <li class="nav-item w-50">
                            <a href="/Acceso/IniciarSesion" class="nav-link text-center">Iniciar Sesión</a>
                        </li>
                        <li class="nav-item w-50">
                            <a href="/Acceso/CrearCuenta" class="nav-link text-center">Crear Cuenta</a>
                        </li>
                    </ul>
                </div>
                <div class="card-content">
                    <div class="row">
                        <div class="col-md-12">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @RenderSection("Scripts", required: false)

    <script>
        $(function(){
            var current=location.pathname;
            $('.nav-tabs li a').each(function(){
                var $this=$(this);
                if(current.indexOf($this.attr('href'))!==-1){
                    //$this.removeClass("active");
                    $this.addClass('active_color');
                }else{
                    $this.addClass('inActive_color');
                }
            })
        })
    </script>
}

@* @section Scripts2{
    @RenderSection("Scripts2", required: false)
} *@

Git_FarmatodoWeb/FarmatodoWeb/Views/Shared/_RolPartial.cshtml
@using FarmatodoWeb.Models
@using Microsoft.AspNetCore.Http
@model Modelos

@{
    var Logueado=AppHttpContext.Current.Session.GetString("Logueado");
}

<ul class="navbar-nav flex-grow-1">
@if(PersonaBase.Id>0 && Logueado!=null){
    @if(PersonaBase.Rol.Equals("Administrador")){
        <li class="nav-item">
            <a class="nav-link" asp-action="AdministradorV1" asp-controller="Administrador" id="letra">V1 (Solo ve el Administrador)</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="letra">Administrar <span class="caret"></span></a>
            <div class="nav-item dropdown-menu" id="navegacion">
                <a class="nav-link" asp-action="AdministradorV1" asp-controller="Administrador" id="letra">Compras</a>
                <a class="nav-link" asp-action="AdministradorV1" asp-controller="Administrador" id="letra">Ventas</a>
                <a class="nav-link" asp-action="AdministradorV1" asp-controller="Administrador" id="letra">Productos</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-action="AdministradorV2" asp-controller="Administrador" id="letra">V2 (Solo ve el Administrador)</a>
        </li>
    }else if(PersonaBase.Rol.Equals("Cliente")){
        <li class="nav-item">
            <a class="nav-link" asp-action="ClienteV1" asp-controller="Cliente" id="letra">V1 (Solo ve el Cliente)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-action="ClienteV2" asp-controller="Cliente" id="letra">V2 (Solo ve el Cliente)</a>
        </li>
    }else{
    }
    Console.WriteLine("(Rol) Rol: "+PersonaBase.Rol+" | Cliente: "+PersonaBase.Nombre);
}else{
}